### ISSUE TITLE
C++ Destructors are not called

### ISSUE THREAD

**Issue by niansa** [ivmai/bdwgc#392] opened 2021-11-24 15:40 UTC
Hey, try this little piece of code:

    #include <gc/gc_cpp.h>
    #include <iostream>
    #include <string>
    
    
    
    int main() {
        GC_INIT();
    
        for (;;) {
            auto test = new (GC) std::string;
            *test = "Hello world! How are you?";
        }
    }

It will end with the following error:

    GC Warning: USE_PROC_FOR_LIBRARIES + GC_LINUX_THREADS performs poorly.
    Too many GC-allocated memory sections: Increase MAX_HEAP_SECTS
    16:37:17: The program has unexpectedly finished.

Is that a bug? Or just a users fault?

Edit: The string destructor never seems to be called!

Edit2: Manually issuing `delete` seems to call the destructor?

**Comment by ivmai** [comment] 2021-11-24 19:32
Cannot reproduce on master (I tried on Linux/x64 and on Cygwin/x64).
Which bdwgc version? Which OS and arch?

**Comment by niansa** [comment] 2021-11-25 04:33
I'm on current master, opensuse tumbleweed, x86_64.
Seems like the real problem is that destructors simply don't get called for some reason

**Comment by niansa** [comment] 2021-11-25 05:39
I tried the same in Termux now - same problem.
The lib is configured with -Denable_cplusplus=on

**Comment by ivmai** [comment] 2021-11-25 07:34
> Seems like the real problem is that destructors simply don't get called for some reason

Please provide the failing sample code, I tried the above one (with some modifications), it finishes correctly:
```
#include "gc_cpp.h"
#include <iostream>
#include <string>

int main() {
    GC_INIT();

    for (int i = 0; i < 1000000; i++) {
        auto test = new (GC) std::string;
        *test = "Hello world! How are you?";
    }
    std::cout << "Done" << std::endl;
    return 0;
}
```
I've used this command for building the test (just for simplicity):
g++ -I include this_test.cc gc_cpp.cc gc_badalc.cc extra/gc.c

**Comment by niansa** [comment] 2021-11-25 12:39
Interesting. That code doesn't fail for me either. But as soon as I make the loop infinite it fails after about 10 seconds.

Also here is an example of the destructor never getting called:

    #include <iostream>
    #include <cstdint>
    #include <gc/gc_cpp.h>
    
    class Test {
    public:
            ~Test() {
                    std::clog << "Destructor called" << std::endl;
                }
                uint64_t v;
    };

    int main() {
            std::cout << "Hello world!" << std::endl;
            auto t = new (GC) Test;
    }

**Comment by ivmai** [comment] 2021-11-25 15:53
> Also here is an example of the destructor never getting called

No, the test case is incorrect. Even though t is declared on the stack, t will probably be remain on the stack even after termination of main(), thus GC will consider it live. (Not to mention GC is not required to happen at process exit.)

**Comment by ivmai** [comment] 2021-11-25 15:57
> Interesting. That code doesn't fail for me either. But as soon as I make the loop infinite it fails after about 10 seconds.

1. Try bigger number of iterations.
2. set GC_PRINT_STATS=1 environment variable and check heap size after every garbage collector (it is printed to console) - if it is growing then the garbage is not reclaimed - need to be investigate in such case.
3. Try compiling code containing unlimited loop with -O0 option (i.e. disable code optimizations).

**Comment by niansa** [comment] 2021-11-25 16:19
> > Also here is an example of the destructor never getting called
> 
> No, the test case is incorrect. Even though t is declared on the stack, t will probably be remain on the stack even after termination of main(), thus GC will consider it live. (Not to mention GC is not required to happen at process 

Ahh... Lol GC is complicated

**Comment by niansa** [comment] 2021-11-25 16:27
>     2. set GC_PRINT_STATS=1 environment variable and check heap size after every garbage collector (it is printed to console) - if it is growing then the garbage is not reclaimed - need to be investigate in such case

The heap size keeps growing until the end where it keeps trying to do full world-stop collection until it finally crashes.
Here is my code:

    for (size_t i = 0xffffffffffffffff; i != 0; i--) {
        auto test = new (GC) std::string;
        *test = "Hello world! How are you?";
    }

And here is the log:

https://www.toptal.com/developers/hastebin/uberoyumom

**Comment by niansa** [comment] 2021-11-25 16:50
> > Also here is an example of the destructor never getting called
> 
> No, the test case is incorrect. Even though t is declared on the stack, t will probably be remain on the stack even after termination of main(), thus GC will consider it live. (Not to mention GC is not required to happen at process exit.)

Try this piece of code then:

    class Test {
    public:
        ~Test() {
            std::cerr << "Destruction!!" << std::endl;
            abort();
        }
    };
    
    int main() {
        GC_INIT();
    
        for (size_t i = 0xffffffffffffffff; i != 0; i--) {
            auto test = new (GC) std::string;
            *test = "Hello world! How are you?";
            if (i % 20 == 0) {
                test = reinterpret_cast<std::string*>(new (GC) Test);
            }
        }
    }

This should make the collector collect the `Test` class, right?

**Comment by niansa** [comment] 2021-11-25 17:57
![image](https://user-images.githubusercontent.com/20720267/143485517-8015424a-1c45-4378-abe1-c04fe16e1cf2.png)
It almost looks like it cleans up the std::string instances themself but not the memory allocated by it.

**Comment by niansa** [comment] 2021-11-25 17:58
Here is another example:

    #include <gc/gc_cpp.h>
    #include <iostream>
    #include <new>
    
    
    
    class Test {
        char *t;
    
    public:
        Test() {
            t = new char[1000000000];
            t[10] = '\n';
        }
    
        ~Test() {
            delete t;
            std::cerr << "Destruction!!" << std::endl;
            abort();
        }
    };
    
    int main() {
        GC_INIT();
    
        for (size_t i = 0xffffffffffffffff; i != 0; i--) {
            auto test = new (GC) Test;
        }
    }

**Comment by ivmai** [comment] 2021-11-25 18:33
> GC Warning: USE_PROC_FOR_LIBRARIES + GC_LINUX_THREADS performs poorly.

It seems you are building with --enable-redirect-malloc option. Is the issue reproduced w/o it?

**Comment by niansa** [comment] 2021-11-26 16:53
I am actually building without it. I just ran `./configure --enable-cplusplus`

**Comment by niansa** [comment] 2021-11-26 16:58
Oh interesting I still had old shared lib versions installed that used redirect-malloc. I replaced those with non-redirect-malloc ones and get a different result now: the heap just keeps growing and growing until the program gets killed by Linux because of OOM

**Comment by niansa** [comment] 2021-12-14 09:23
So yes, problem persists.

**Comment by ivmai** [comment] 2022-03-12 09:36
> Here is another (failing) example:
> ...
> auto test = new (GC) Test;

I've reproduced this (on Cygwin/x64, g++ (GCC) 11.2.0):
g++ -O0 -g -I include t.cc extra/gc.c gc_badalc.cc && ./a.out

The destructor is not called because cleanup is 0:
operator new (size=8, gcp=UseGC, cleanup=0x0, clientData=0x0) at include/gc/gc_cpp.h:527

**Comment by ivmai** [comment] 2022-03-12 09:57
As said in [gc_cpp.h](https://github.com/ivmai/bdwgc/blob/166d6e07dc9d54599ab1ecba46dbca530b4e7217/include/gc/gc_cpp.h#L65):
> An object derived from "gc_cleanup" or containing a member derived
> from "gc_cleanup" has a default clean-up function that invokes the
> object's destructors.

Thus, the issue is not in GC, the test should be fixed e.g. as:
class Test: public gc_cleanup

**Closed by ivmai** 2022-03-12 09:57 UTC

**Comment by niansa** [comment] 2023-02-06 10:17
Makes total sense, now that I think of it. Thanks for the awesome help tho :-)
