### ISSUE TITLE
`un-mprotect failed` on Ubuntu with out-of-memory error

### ISSUE THREAD

**Issue by UltimatePea** [ivmai/bdwgc#579] opened 2023-10-23 14:06 UTC
I am not sure if this is a good place to ask. Some of my compiled programs that run on linux will throw `un-mprotect failed` error. This issue will not occur on windows or Mac. Is there any way to fix this?

**Comment by ivmai** [comment] 2023-10-23 14:20
Please give more info. Which configuration of libgc? which libgc version? (is it reproduced with master?)

**Comment by UltimatePea** [comment] 2023-10-24 18:00
Thanks for helping! I am using the default version `apt install libgc-dev` that is bundled with Ubuntu 22.04 LTS (configured by the default package management system). 

The issue is hard to reproduce: it usually occurs if the program runs for > 20 minutes with continuous allocations. See for example, this log: https://github.com/yuyan-lang/yuyan/actions/runs/5813820793/job/15762191733 (notice the `un-mprotect failed along the last lines of log). If I shorten/simplify the program or even slightly change how a program is compiled, the issue usually disappears on subsequent runs. 

It would be sometime before I check if it is reproduced with the latest master. I will follow up here with more details when I get a chance to check. 

This issue never occurs on macOS. So I am also wondering if there is a way to circumvent this issue.

**Comment by ivmai** [comment] 2023-10-24 18:08
Please give me exact libgc version - it could be seen in /usr/invlude/gc/gc_version.h
Then I could check if there any related fix applied since that verison.

**Comment by UltimatePea** [comment] 2023-10-25 00:59
My gc_version.h shows:

```
/* The policy regarding version numbers: development code has odd       */
/* "minor" number (and "micro" part is 0); when development is finished */
/* and a release is prepared, "minor" number is incremented (keeping    */
/* "micro" number still zero), whenever a defect is fixed a new release */
/* is prepared incrementing "micro" part to odd value (the most stable  */
/* release has the biggest "micro" number).                             */

/* The version here should match that in configure/configure.ac */
/* Eventually this one may become unnecessary.  For now we need */
/* it to keep the old-style build process working.              */
#define GC_TMP_VERSION_MAJOR 8
#define GC_TMP_VERSION_MINOR 0
#define GC_TMP_VERSION_MICRO 6 /* 8.0.6 */

#ifdef GC_VERSION_MAJOR
# if GC_TMP_VERSION_MAJOR != GC_VERSION_MAJOR \
     || GC_TMP_VERSION_MINOR != GC_VERSION_MINOR \
     || GC_TMP_VERSION_MICRO != GC_VERSION_MICRO
#   error Inconsistent version info.  Check README.md, include/gc_version.h and configure.ac.
# endif
#else
# define GC_VERSION_MAJOR GC_TMP_VERSION_MAJOR
# define GC_VERSION_MINOR GC_TMP_VERSION_MINOR
# define GC_VERSION_MICRO GC_TMP_VERSION_MICRO
#endif /* !GC_VERSION_MAJOR */

#endif
```

**Comment by ivmai** [comment] 2023-10-25 08:18
> Please give me exact libgc version - it could be seen in /usr/include/gc/gc_version.h Then I could check if there any related fix applied since that version.

I don't see any relevant fixes since v8.0.6, but you ideally please try to reproduce it on master or at least on https://github.com/ivmai/bdwgc/releases/tag/v8.0.10

**Comment by UltimatePea** [comment] 2023-12-19 12:59
I speculate that the root issue of this problem is that repeated allocations of large blocks of memory (for over 30 seconds with nearly no other computation) will overflow some system limit. 

I haven't had a chance to try the master yet, as the compiler is not set up to allow customizations of library paths. The workaround is to break the program into smaller chunks so the compiler would not generate codes that allocate memory that often.

**Comment by ivmai** [comment] 2023-12-19 15:39
> I haven't had a chance to try the master yet.

I think you could try release-8_0 branch. It, at least contains all fixes applied to master.

> I speculate that the root issue of this problem is that repeated allocations of large blocks of memory

Maybe. BTW Is COUNT_UNMAPPED_REGIONS defined (in gcconfig.h) when compiling libgc?

**Comment by UltimatePea** [comment] 2023-12-19 16:16
> I think you could try release-8_0 branch. It, at least contains all fixes applied to master.

Thank you! I am going to try master. 

> Maybe. BTW Is COUNT_UNMAPPED_REGIONS defined (in gcconfig.h) when compiling libgc?

This string is currently not found in `/usr/include/gc/gc_config_macros.h`. I am going to try master with default configurations.

**Comment by UltimatePea** [comment] 2023-12-19 17:27
Compiling on latest master with static libraries and default options, I am getting 
```
un-mprotect vdb failed at 0x7fad8b0b3000 (length 4096), errno= 12
un-mprotect vdb failed
fish: Job 1, './yy_bs --mode=worker --worker-…' terminated by signal SIGABRT (Abort)
```

**Comment by UltimatePea** [comment] 2023-12-19 17:32
Please let me know if you need any other information. This currently has become a blocking issue for me. I am happy to assist you by providing more information.

**Comment by UltimatePea** [comment] 2023-12-19 17:48
Disabling incremental collection seems to be a temporary fix.

**Comment by ivmai** [comment] 2023-12-19 20:18
> My observation is that enabling incremental collection by calling `GC_enable_incremental` after `GC_init`, the program will use threads for parallel collection, but not calling it, the program won't be using additional threads for gc. This incurs a performancs penalty.

This is a different issue, could you please create it.

**Comment by ivmai** [comment] 2023-12-19 20:26
> Compiling on latest master with static libraries and default options, I am getting
un-mprotect vdb failed at 0x7fad8b0b3

I think I understand the root cause: limit on virtual memory regions (64K) in Linux. I need to think of the proper solution.

At the same time, in case if master, I don't understand why mprotect vdb is used but not SOFT_VDB implementation. I assume your are running Ubuntu on x86_64.

**Comment by ivmai** [comment] 2023-12-19 20:32
Could you please run gctest (of master) and provide the output?

**Comment by UltimatePea** [comment] 2023-12-19 20:39
```
~/y/b/out (master|✔) $ ./gctest
Switched to incremental mode
Emulating dirty bits with mprotect/signals
Completed 6 tests
Allocated 11792955 collectable objects
Allocated 1224 uncollectable objects
Allocated 720438 atomic objects
Reallocated 36 objects
Garbage collection after fork is tested too
Finalized 13474/13474 objects - finalization is probably OK
Total number of bytes allocated is 1157564640
Total memory use by allocated blocks is 2375680 bytes
Final heap size is 520192 bytes
Obtained 63152128 bytes from OS (of which 50126848 bytes unmapped)
Final number of reachable objects is 3469
Full/world-stopped collections took 233/1050 ms
Completed 3935 collections (using 16 marker threads)
Collector appears to work
                                                                                                                                                                                                                                                   [ 3s334 | Dec 19 03:39PM ]
~/y/b/out (master|✔) $ 
```

**Comment by ivmai** [comment] 2023-12-19 21:18
> ./gctest
> Switched to incremental mode
> Emulating dirty bits with mprotect/signals
> Completed 6 tests

Strange, output should be different, e.g. as in https://app.travis-ci.com/github/ivmai/bdwgc/jobs/614968861
```
cat gctest.log
Switched to incremental mode
Reading dirty bits from /proc
Completed 6 tests
```

Please run `GC_PRINT_VERBOSE_STATS=1 ./gctest |& head -n15`

**Comment by ivmai** [comment] 2023-12-19 21:29
>> un-mprotect failed
>
> I think I understand the root cause: limit on virtual memory regions (64K) in Linux. I need to think of the proper solution.

This is similar to #324 and the solution (fix) should be similar (maintain GC_num_dirty_regions and unprotect whole region if GC_num_dirty_regions+GC_num_unmapped_regions reaches GC_UNMAPPED_REGIONS_SOFT_LIMIT).

**Comment by UltimatePea** [comment] 2023-12-19 21:32
> Please run GC_PRINT_VERBOSE_STATS=1 ./gctest |& head -n15
```
$ GC_PRINT_VERBOSE_STATS=1 ./gctest |& head -n15
Got 65536 bytes from OS
Initializing mprotect virtual dirty bit implementation
Soft-dirty bit is not supported by kernel
Recycle 12288/16384 scratch-allocated bytes at 0x7f616ed06020
Grew heap sections array to 32 elements
Got 65536 bytes from OS
Got 65536 bytes from OS
In-use heap: 0% (0 KiB pointers + 0 KiB other)
Got 65536 bytes from OS
Grow heap to 76 KiB after 0 bytes allocated
Got 65536 bytes from OS
Number of processors: 32
Will retry suspend and restart signals if necessary
Initiating full world-stop collection!
0 bytes in heap blacklisted for interior pointers
```

**Comment by ivmai** [comment] 2023-12-20 05:04
> Soft-dirty bit is not supported by kernel

Strange, I can't reproduce it on my Ubuntu 22.04 x86_64 host. Why is detect_soft_dirty_supported() returning false? (you could rebuild libgc by `./configure --disable-shared --disable-threads && make check CFLAGS_EXTRA="-O0 -g"` and set breakpoint in the mentioned function in the debugger.

What's your kernel version? I've tested it on 5.15.0-88-generic.

**Comment by ivmai** [comment] 2024-02-12 20:42
> Compiling on latest master with static libraries and default options, I am getting
> `un-mprotect vdb failed at 0x7fad8b0b3000 (length 4096), errno= 12`

Please try on the latest master - the issue should be fixed.

**Closed by ivmai** 2024-02-12 20:42 UTC
