### ISSUE TITLE
test failures on ppc64 after recent change (too big number of recycled bytes)

### ISSUE THREAD

**Issue by sharkcz** [ivmai/bdwgc#371] opened 2021-09-15 09:17 UTC
Since commit dc98162d7e787e9af1ff99c07eef0b0280a44a7a a number of tests started to fail on our ppc64 system (Fedora 28 with gcc 8.3.1). Other platforms in our CI look good.
````
================================
   gc 8.1.0: ./test-suite.log
================================

# TOTAL: 17
# PASS:  11
# SKIP:  0
# XFAIL: 0
# FAIL:  6
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: cordtest
==============

Deallocating excessively large block.  Too large an allocation?
FAIL cordtest (exit status: 134)

FAIL: gctest
============

Deallocating excessively large block.  Too large an allocation?
FAIL gctest (exit status: 134)

FAIL: staticrootstest
=====================

Deallocating excessively large block.  Too large an allocation?
FAIL staticrootstest (exit status: 134)

FAIL: test_cpp
==============

Deallocating excessively large block.  Too large an allocation?
FAIL test_cpp (exit status: 134)

FAIL: disclaim_test
===================

Deallocating excessively large block.  Too large an allocation?
FAIL disclaim_test (exit status: 134)

FAIL: disclaim_weakmap_test
===========================

Deallocating excessively large block.  Too large an allocation?
FAIL disclaim_weakmap_test (exit status: 134)

````

**Comment by ivmai** [comment] 2021-09-15 20:32
> Since commit dc98162 a number of tests started to fail on our ppc64 system

1. Do I understand correct that exactly the mentioned commit breaks the builds? E.g. on reproduced on commit b7a182848.
2. If yes, could you please try build of commit dc98162 and run: GC_PRINT_STATS=1 ./gctest. Is "Soft-dirty bit is not supported by kernel" message printed by it?

**Comment by ivmai** [comment] 2021-09-15 20:34
It looks like hhdr->hb_sz is corrupted somehow.

**Comment by ivmai** [comment] 2021-09-16 05:17
Is  the platform big-endian? (If yes, then probably I know how to fix it.)

**Comment by ivmai** [comment] 2021-09-16 07:17
Relates to issue #265

**Comment by sharkcz** [comment] 2021-09-16 07:47
> > Since commit [dc98162](https://github.com/ivmai/bdwgc/commit/dc98162d7e787e9af1ff99c07eef0b0280a44a7a) a number of tests started to fail on our ppc64 system
> 
>     1. Do I understand correct that exactly the mentioned commit breaks the builds? E.g. on reproduced on commit [b7a1828](https://github.com/ivmai/bdwgc/commit/b7a182848a85f9663f4d3d3fd5759782fe0cba3b).

yes, commit b7a1828 is the last OK, commit dc98162 is the one where tests start to fail

> 
>     2. If yes, could you please try build of commit [dc98162](https://github.com/ivmai/bdwgc/commit/dc98162d7e787e9af1ff99c07eef0b0280a44a7a) and run: GC_PRINT_STATS=1 ./gctest. Is "Soft-dirty bit is not supported by kernel" message printed by it?

````
[sharkcz@tyan-openpower-01 gc]$ LANG=C GC_PRINT_STATS=1 ./gctest
Soft-dirty bit is not supported by kernel
Recycle 18446744073709486080 scratch-allocated bytes at 0x7fffaecf2020
Deallocating excessively large block.  Too large an allocation?
Aborted (core dumped [obraz paměti uložen])
````

and yes, ppc64 is big endian (running kernel 5.0.16)

**Comment by ivmai** [comment] 2021-09-16 08:02
> Is the platform big-endian? (If yes, then probably I know how to fix it.)

I've fixed it in commit https://github.com/ivmai/bdwgc/commit/f457c25563cf9f4d10baf71500f0dd75f160d752 (master)

> LANG=C GC_PRINT_STATS=1 ./gctest
> Soft-dirty bit is not supported by kernel

Hmm. It looks like the issue is not fixed by https://github.com/ivmai/bdwgc/commit/f457c25563cf9f4d10baf71500f0dd75f160d752, the bug is somewhere else.
Please try latest master, it should hide the bug (but not fix it).

**Comment by ivmai** [comment] 2021-09-16 08:03
> Recycle 18446744073709486080 scratch-allocated bytes at 0x7fffaecf2020

Hmm. Very big value (number of bytes)

**Comment by ivmai** [comment] 2021-09-16 08:07
I think I know there the bug is.

> Yes, commit b7a1828 is the last OK, commit dc98162 is the one where tests start to fail
> LANG=C GC_PRINT_STATS=1 ./gctest

Could you please retry this command on commit dc98162 with ./configure --enable-gc-assertions

**Comment by sharkcz** [comment] 2021-09-16 08:19
with the recent master that includes commit f457c25563cf9f4d10baf71500f0dd75f160d752 the tests are passing again

**Comment by sharkcz** [comment] 2021-09-16 08:20
also ppc64 is using 64K kernel page size (in some distros), same as ppc64le (but this is little endian)

**Comment by sharkcz** [comment] 2021-09-16 08:29
and for the record, I haven't seen any issue on s390x which is also big endian (but 4K page size)

**Comment by ivmai** [comment] 2021-09-16 21:15
>> Recycle 18446744073709486080 scratch-allocated bytes at 0x7fffaecf2020

> Hmm. Very big value (number of bytes)
> I think I know there the bug is.

Fixed by https://github.com/ivmai/bdwgc/commit/500361e0f102bcc03f47d190250424ce1c60e024

**Comment by ivmai** [comment] 2021-09-16 21:19
> also ppc64 is using 64K kernel page size (in some distros), same as ppc64le (but this is little endian)

Yes, big page size (together with incorrect handling of big-endian) tickled the bug.

> and for the record, I haven't seen any issue on s390x which is also big endian (but 4K page size)

Because SOFT_VDB is disabled by default on s390x.

**Closed by ivmai** 2021-09-16 21:19 UTC
